api_user_following:
    pattern: /following
    defaults:
        _controller: WhootUserBundle:Profile:following
        _format: json
    requirements:
        _method: GET

api_user_followers:
    pattern: /followers
    defaults:
        _controller: WhootUserBundle:Profile:followers
        _format: json
    requirements:
        _method: GET