### SECURITY
fos_user_security_login:
    pattern:  /login.{_format}
    defaults: { _controller: FOSUserBundle:Security:login, _format: html }
    requirements:
        _format:    html|xml

fos_user_security_check:
    pattern:  /login.{_format}
    defaults: { _controller: FOSUserBundle:Security:login, _format: xml }
    requirements:
        _format:    html|xml

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
###

### PROFILE
user_upload_picture:
    pattern:  /upload-picture
    defaults: { _controller: WhootUserBundle:Profile:uploadPicture }
    requirements:
        _method: POST

user_followers:
    pattern:  /{username}/followers
    defaults: { _controller: WhootUserBundle:Profile:followers }
    requirements:
      _method: GET

user_following:
    pattern:  /{username}/following
    defaults: { _controller: WhootUserBundle:Profile:following }
    requirements:
      _method: GET

user_settings:
    pattern:  /{username}/settings
    defaults: { _controller: WhootUserBundle:Profile:settings }
    requirements:
      _method: GET

user_profile_show:
    pattern: /profile/{username}
    defaults: { _controller: FOSUserBundle:Profile:show, _format: html }
    requirements:
        _method: GET

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
###

### REGISTRATION
user_registration_register:
    pattern: /register.{_format}
    defaults: { _controller: FOSUserBundle:Registration:register, _format: html }
    requirements:
        _method: GET|POST

user_registration_confirmed:
    pattern: /register/confirmed.{_format}
    defaults: { _controller: FOSUserBundle:Registration:confirmed, _format: html }
    requirements:
        _method: GET

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
###

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password