follow_toggle:
    pattern:  /toggle/{userId}
    defaults: { _controller: SocialiteBundle:Follow:toggle, userId: 0 }
    requirements:
        _method: GET|POST
        objectId: \d+

follow_show:
    pattern:  /{userId}
    defaults: { _controller: SocialiteBundle:Follow:show, _format: html }
    requirements:
        _method: GET
        userId: \d+
        format: html|xml