security:
    resource: "@SocialiteBundle/Resources/config/routing/security.yml"

user:
    resource: "@SocialiteBundle/Resources/config/routing/user.yml"
    prefix:   /u
    
post:
    resource: "@SocialiteBundle/Resources/config/routing/post.yml"
    prefix:   /p

follow:
    resource: "@SocialiteBundle/Resources/config/routing/follow.yml"
    prefix:   /f

feed_filter_toggle:
    pattern:  /ac/tf/{postType}
    defaults: { _controller: SocialiteBundle:Core:toggleFeedFilter }
    requirements:
        postType:  working|low_in|low_out|big_out
        _method: GET|POST

feed_filter_change:
    pattern:  /ac/cf/{key}/{value}
    defaults: { _controller: SocialiteBundle:Core:changeFeedFilter }
    requirements:
        key:  feedSort
        value: popularity|created
        _method: GET|POST

homepage:
    pattern:  /
    defaults: { _controller: SocialiteBundle:Core:home }