parameters:
    socialite.core_manager.class:                  Socialite\SocialiteBundle\Entity\CoreManager
    socialite.user_manager.class:                  Socialite\SocialiteBundle\Entity\UserManager
    socialite.post_manager.class:                  Socialite\SocialiteBundle\Entity\PostManager
    socialite.ping_manager.class:                  Socialite\SocialiteBundle\Entity\PingManager

services:
    socialite.core_manager:
        class:        %socialite.core_manager.class%
        arguments:    ["@request", "@router", "@security.context"]
        scope:       request
    socialite.user_manager:
        class:        %socialite.user_manager.class%
        arguments:    ["@doctrine.orm.default_entity_manager"]
    socialite.post_manager:
        class:        %socialite.post_manager.class%
        arguments:    ["@socialite.user_manager", "@doctrine.orm.default_entity_manager"]
    socialite.ping_manager:
        class:        %socialite.ping_manager.class%
        arguments:    ["@doctrine.orm.default_entity_manager"]