imports:
    - { resource: "@WhootUserBundle/Resources/config/config.yml" }
#    - { resource: "@WhootVoteBundle/Resources/config/config.yml" }
#    - { resource: "@WhootNotificationBundle/Resources/config/config.yml" }

    - { resource: "@WhootBundle/Resources/config/manager.yml" }
    - { resource: "@WhootBundle/Resources/config/form.xml" }