parameters:
    whoot.core_manager.class:                  Whoot\WhootBundle\Entity\CoreManager
    whoot.post_manager.class:                  Whoot\WhootBundle\Entity\PostManager
    whoot.invite_manager.class:                Whoot\WhootBundle\Entity\InviteManager
    whoot.word_manager.class:                  Whoot\WhootBundle\Entity\WordManager
    whoot.ping_manager.class:                  Whoot\WhootBundle\Entity\PingManager
    whoot.comment_manager.class:               Whoot\WhootBundle\Entity\CommentManager
    whoot.list_manager.class:                  Whoot\WhootBundle\Entity\LListManager
    whoot.location_manager.class:              Whoot\WhootBundle\Entity\LocationManager

services:
    whoot.core_manager:
        class:        %whoot.core_manager.class%
        arguments:    ["@request", "@router", "@security.context"]
        scope:       request
    whoot.post_manager:
        class:        %whoot.post_manager.class%
        arguments:    ["@whoot.user_manager", "@doctrine.orm.default_entity_manager"]
    whoot.invite_manager:
        class:        %whoot.invite_manager.class%
        arguments:    ["@whoot.user_manager", "@doctrine.orm.default_entity_manager"]
    whoot.word_manager:
        class:        %whoot.word_manager.class%
        arguments:    ["@doctrine.orm.default_entity_manager"]
    whoot.ping_manager:
        class:        %whoot.ping_manager.class%
        arguments:    ["@doctrine.orm.default_entity_manager"]
    whoot.comment_manager:
        class:        %whoot.comment_manager.class%
        arguments:    ["@doctrine.orm.default_entity_manager", "@security.context"]
    whoot.list_manager:
        class:        %whoot.list_manager.class%
        arguments:    ["@whoot.user_manager", "@doctrine.orm.default_entity_manager", "@security.context"]
    whoot.location_manager:
        class:        %whoot.location_manager.class%
        arguments:    ["@doctrine.orm.default_entity_manager"]