parameters:
    whoot.manager.core.class:                  Whoot\WhootBundle\Entity\CoreManager
    whoot.manager.post.class:                  Whoot\WhootBundle\Entity\PostManager
    whoot.manager.invite.class:                Whoot\WhootBundle\Entity\InviteManager
    whoot.manager.word.class:                  Whoot\WhootBundle\Entity\WordManager
    whoot.manager.ping.class:                  Whoot\WhootBundle\Entity\PingManager
    whoot.manager.comment.class:               Whoot\WhootBundle\Entity\CommentManager
    whoot.manager.list.class:                  Whoot\WhootBundle\Entity\LListManager
    whoot.manager.location.class:              Whoot\WhootBundle\Entity\LocationManager

services:
    whoot.manager.core:
        class:        %whoot.manager.core.class%
        arguments:    ["@request", "@router", "@security.context"]
        scope:       request
    whoot.manager.post:
        class:        %whoot.manager.post.class%
        arguments:    ["@doctrine.orm.default_entity_manager", "@whoot.manager.user"]
    whoot.manager.invite:
        class:        %whoot.manager.invite.class%
        arguments:    ["@doctrine.orm.default_entity_manager", "@whoot.manager.user"]
    whoot.manager.word:
        class:        %whoot.manager.word.class%
        arguments:    ["@doctrine.orm.default_entity_manager"]
    whoot.manager.ping:
        class:        %whoot.manager.ping.class%
        arguments:    ["@doctrine.orm.default_entity_manager", "@whoot.manager.notification"]
    whoot.manager.comment:
        class:        %whoot.manager.comment.class%
        arguments:    ["@doctrine.orm.default_entity_manager", "@security.context"]
    whoot.manager.list:
        class:        %whoot.manager.list.class%
        arguments:    ["@doctrine.orm.default_entity_manager", "@security.context", "@whoot.manager.user"]
    whoot.manager.location:
        class:        %whoot.manager.location.class%
        arguments:    ["@doctrine.orm.default_entity_manager"]