parameters:
    whoot.core_manager.class:                  Whoot\WhootBundle\Entity\CoreManager
    whoot.user_manager.class:                  Whoot\WhootBundle\Entity\UserManager
    whoot.post_manager.class:                  Whoot\WhootBundle\Entity\PostManager
    whoot.ping_manager.class:                  Whoot\WhootBundle\Entity\PingManager

services:
    whoot.core_manager:
        class:        %whoot.core_manager.class%
        arguments:    ["@request", "@router", "@security.context"]
        scope:       request
    whoot.user_manager:
        class:        %whoot.user_manager.class%
        arguments:    ["@doctrine.orm.default_entity_manager"]
    whoot.post_manager:
        class:        %whoot.post_manager.class%
        arguments:    ["@whoot.user_manager", "@doctrine.orm.default_entity_manager"]
    whoot.ping_manager:
        class:        %whoot.ping_manager.class%
        arguments:    ["@doctrine.orm.default_entity_manager"]