imports:
    - { resource: parameters.ini }
    - { resource: security.yml }
    - { resource: "@WhootBundle/Resources/config/config.yml" }

framework:
    secret:        %secret%
    charset:       UTF-8
    esi: ~
    csrf_protection: true
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enabled: true, enable_annotations: true }
    form:          true
    translator:    { fallback: en }
    templating:
        engines: ['twig']
    session:
        default_locale: %locale%
        lifetime:       3600
        auto_start:     true
        storage_id:     session.storage.pdo
    annotations:
        cache: file
        debug: %kernel.debug%

parameters:
    pdo.db_options:
        db_table: session
        db_id_col: session_id
        db_data_col: session_value
        db_time_col: session_time

services:
    session.storage.pdo:
        class:     Symfony\Component\HttpFoundation\SessionStorage\PdoSessionStorage
        arguments: [@pdo, {}, %pdo.db_options%]

    pdo:
        class: PDO
        arguments:
                dsn:      "mysql:dbname=%database_name%"
                user:     %database_user%
                password: %database_password%
                
# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        logging:  %kernel.debug%

    orm:
        auto_mapping: true
        auto_generate_proxy_classes: true
        proxy_namespace: Proxies
        proxy_dir: %kernel.cache_dir%/doctrine/orm/Proxies
        default_entity_manager: default
        metadata_cache_driver: array
        query_cache_driver: array
        result_cache_driver: array
        
# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
#    read_from:      %kernel.root_dir%/../web
#    write_to:       %kernel.root_dir%/../web
    filters:
        cssrewrite: ~
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

# This came with the symfony-standard distribution, not sure what it is.
jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

gravatar: ~

# FriendsOfSymfony UserBundle Configuration
fos_user:
        db_driver:     orm
        firewall_name: main
        user_class:    Whoot\WhootBundle\Entity\User
        use_listener:  true
        from_email:     { marc@thewhoot.com: Admin }
#        profile:
#            form:
#                type:               FOS\UserBundle\Form\ProfileFormType
#                handler:            FOS\UserBundle\Form\ProfileFormHandler
#                name:               fos_user_profile_form
#                validation_groups:  [Profile]
#        change_password:
#            form:
#                type:               FOS\UserBundle\Form\ChangePasswordFormType
#                handler:            FOS\UserBundle\Form\ChangePasswordFormHandler
#                name:               fos_user_change_password_form
#                validation_groups:  [ChangePassword]
        registration:
#            confirmation:
#                from_email: ~
#                enabled:    false
#                template:   FOSUserBundle:Registration:email.txt.twig
            form:
                type:               Whoot\WhootUserBundle\Form\RegistrationFormType
#                handler:            FOS\UserBundle\Form\RegistrationFormHandler
#                name:               fos_user_registration_form
#                validation_groups:  [Registration]
#        resetting:
#            token_ttl: 86400
#            email:
#                from_email: ~
#                template:   FOSUserBundle:Resetting:email.txt.twig
#            form:
#                type:               FOS\UserBundle\Form\ResettingFormType
#                handler:            FOS\UserBundle\Form\ResettingFormHandler
#                name:               fos_user_resetting_form
#                validation_groups:  [ResetPassword]
#        service:
#            mailer:                 fos_user.util.mailer.default
#            email_canonicalizer:    fos_user.util.email_canonicalizer.default
#            username_canonicalizer: fos_user.util.username_canonicalizer.default
#        encoder:
#            algorithm:          sha512
#            encode_as_base64:   false
#            iterations:         1
#        template:
#            engine: twig
#            theme:  FOSUserBundle::form.html.twig
#        group:
#            group_class:    ~ # Required when using groups
#            form:
#                type:               FOS\UserBundle\Form\GroupFormType
#                handler:            FOS\UserBundle\Form\GroupHandler
#                name:               fos_user_group_form
#                validation_groups:  [Registration]

#            form:
#                user:            ~
#                change_password: ~
#                reset_password:  ~
#            controller:
#                user:      Limelight\LimelightBundle\Controller\UserController
#                security:  Limelight\LimelightBundle\Controller\SecurityController
#        service:
#            mailer: ~
#            email_canonicalizer:    ~
#            username_canonicalizer: ~
#        encoder:
#            algorithm: sha512
#            encode-as-base64: true
#            iterations: 5
#        form_name:
#            user:            ~
#            change_password: ~
#            reset_password:  ~
#        form_validation_groups:
#            user: ~             # This value is an array of groups
#        email:
#            from_email: ~       # { admin@example.com: Sender_name }
#            confirmation:
#                enabled:    ~
#                template:   ~
#            resetting_password:
#                template:   ~
#                token_ttl:  ~
#        template:
#            engine: ~
#            theme:  ~
#        group:
#            class:
#                model: MyProject\MyBundle\Document\Group
#                controller: ~
#                form: ~
#            form_name: ~
#            form_validation_groups: ~