imports:
    - { resource: parameters.ini }
    - { resource: security.yml }
    - { resource: "@WhootBundle/Resources/config/config.yml" }

framework:
    secret:        %secret%
    charset:       UTF-8
    esi: ~
    csrf_protection:
        enabled: true
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enabled: true, annotations: true }
    translator:    { fallback: en }
    templating:
        engines: ['twig']
        assets_version: 0.0.0.1
    session:
        default_locale: %locale%
        lifetime:       3600
        auto_start:     true
        storage_id:     session.storage.pdo

parameters:
    pdo.db_options:
        db_table: session
        db_id_col: session_id
        db_data_col: session_value
        db_time_col: session_time

services:
    session.storage.pdo:
        class:     Symfony\Component\HttpFoundation\SessionStorage\PdoSessionStorage
        arguments: [@pdo, {}, %pdo.db_options%]

    pdo:
        class: PDO
        arguments:
                dsn:      "mysql:dbname=%database_name%"
                user:     %database_user%
                password: %database_password%
                
# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        logging:  %kernel.debug%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                metadata_cache_driver:  array
                query_cache_driver:     array
                result_cache_driver:    array
                mappings:
                    FOSUserBundle: ~
                    WhootBundle: ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    extensions:       [twig.extension.debug]

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
#    read_from:      %kernel.root_dir%/../web
#    write_to:       %kernel.root_dir%/../web
    filters:
        cssrewrite: ~
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

# This came with the symfony-standard distribution, not sure what it is.
jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

# FriendsOfSymfony UserBundle Configuration
fos_user:
        db_driver:     orm
        firewall_name: main
        class:
            model:
                user:      Whoot\WhootBundle\Entity\User
            form:
                user:      Whoot\WhootBundle\Form\UserFormType
#                change_password: ~
#                reset_password:  ~
            controller:
                user:      Whoot\WhootBundle\Controller\UserController
                security:  Whoot\WhootBundle\Controller\SecurityController
#        service:
#            mailer: ~
#            email_canonicalizer:    ~
#            username_canonicalizer: ~
#        encoder:
#            algorithm: sha512
#            encode-as-base64: true
#            iterations: 5
#        form_name:
#            user:            ~
#            change_password: ~
#            reset_password:  ~
#        form_validation_groups:
#            user: ~             # This value is an array of groups
#        email:
#            from_email: ~       # { admin@example.com: Sender_name }
#            confirmation:
#                enabled:    ~
#                template:   ~
#            resetting_password:
#                template:   ~
#                token_ttl:  ~
#        template:
#            engine: ~
#            theme:  ~
#        group:
#            class:
#                model: MyProject\MyBundle\Document\Group
#                controller: ~
#                form: ~
#            form_name: ~
#            form_validation_groups: ~