imports:
    - { resource: parameters.ini }
    - { resource: security.yml }
    - { resource: "@WhootBundle/Resources/config/config.yml" }

framework:
    secret:        %secret%
    charset:       UTF-8
    esi: ~
    csrf_protection: false
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enabled: true, enable_annotations: true }
    form:          true
    translator:    { fallback: en }
    templating:
        engines: ['twig']
    session:
        default_locale: %locale%
        auto_start:     true
        lifetime:       3600
    annotations:
        cache: file
        debug: %kernel.debug%

services:
    whoot.facebook.user:
        class: Whoot\WhootBundle\Security\User\Provider\FacebookProvider
        arguments:
            facebook:    "@fos_facebook.api"
            userManager: "@whoot.manager.user"
            imageManager: "@marbemac.manager.image"
            validator: "@validator"
            
doctrine_mongodb:
    default_database: whoot_%kernel.environment%
    auto_generate_proxy_classes: %kernel.debug%
    connections:
        default:
            server: mongodb://localhost:27017
            options:
                connect: true
    document_managers:
        default:
            metadata_cache_driver: array
            mappings:
                FOSUserBundle: ~
                MarbemacImageBundle: ~
                MarbemacVoteBundle: ~
                MarbemacNotificationBundle: ~
                WhootUserBundle: ~
                WhootBundle: ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
#    read_from:      %kernel.root_dir%/../web
#    write_to:       %kernel.root_dir%/../web
    filters:
        cssrewrite: ~
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

marbemac_notification: ~

marbemac_image: ~

marbemac_vote:
    document_stem: Whoot\WhootBundle\Document

marbemac_analytics:
    use_analytics: true
    analytics:
        manager: Marbemac\AnalyticsBundle\Document\AnalyticsManager

    use_woopra: true
    woopra:
        manager: Marbemac\AnalyticsBundle\Document\WoopraManager
        idle_timeout: 420000 # 7 minutes

# FOS Facebook config
fos_facebook:
    file:   %kernel.root_dir%/../vendor/facebook/src/facebook.php
    alias:  facebook
    cookie: true
    permissions: [email, user_birthday, user_hometown, user_location]

# FriendsOfSymfony UserBundle Configuration
fos_user:
    db_driver:      mongodb
    firewall_name:  main
    user_class:     Whoot\UserBundle\Document\User
    use_listener:   true
    use_username_form_type: false
#    model_manager_name: whoot.manager.user  # change it to the name of your entity/document manager if you don't want to use the default one.
    from_email:
        address: marc@thewhoot.com
        sender_name: Marc
#    profile:
#        form:
#            type:               fos_user_profile
#            handler:            fos_user.profile.form.handler.default
#            name:               fos_user_profile_form
#            validation_groups:  [Profile]
#    change_password:
#        form:
#            type:               fos_user_change_password
#            handler:            fos_user.change_password.form.handler.default
#            name:               fos_user_change_password_form
#            validation_groups:  [ChangePassword]
    registration:
#        confirmation:
#            from_email: # Use this node only if you don't want the global email address for the confirmation email
#                address:        ...
#                sender_name:    ...
#            enabled:    false
#            template:   FOSUserBundle:Registration:email.txt.twig
        form:
            type:               whoot_user_registration
#            handler:            fos_user.registration.form.handler.default
#            name:               fos_user_registration_form
#            validation_groups:  [Registration]
#    resetting:
#        token_ttl: 86400
#        email:
#            from_email: # Use this node only if you don't want the global email address for the resetting email
#                address:        ...
#                sender_name:    ...
#            template:   FOSUserBundle:Resetting:email.txt.twig
#        form:
#            type:               fos_user_resetting
#            handler:            fos_user.resetting.form.handler.default
#            name:               fos_user_resetting_form
#            validation_groups:  [ResetPassword]
#    service:
#        mailer:                 fos_user.util.mailer.default
#        email_canonicalizer:    fos_user.util.email_canonicalizer.default
#        username_canonicalizer: fos_user.util.username_canonicalizer.default
#        user_manager:           fos_user.user_manager.default
#    encoder:
#        algorithm:          sha512
#        encode_as_base64:   false
#        iterations:         1
#    template:
#        engine: twig
#        theme:  FOSUserBundle::form.html.twig
#    group:
#        group_class:    ~ # Required when using groups
#        form:
#            type:               fos_user_group
#            handler:            fos_user.group.form.handler.default
#            name:               fos_user_group_form
#            validation_groups:  [Registration]