imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_staging.yml" }

fos_facebook:
    app_id: 120786798012675
    secret: 772c338ce553ec0008fbf2b266f343a5