imports:
    - { resource: parameters.ini }
    - { resource: security.yml }
    - { resource: "@WhootBundle/Resources/config/config.yml" }

framework:
    secret:        %secret%
    charset:       UTF-8
    esi: ~
    csrf_protection: false
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enabled: true, enable_annotations: true }
    form:          true
    translator:    { fallback: en }
    templating:
        engines: ['twig']
    session:
        default_locale: %locale%
        auto_start:     true
        lifetime:       3600
        storage_id:     session.storage.pdo
    annotations:
        cache: file
        debug: %kernel.debug%

parameters:
    pdo.db_options:
        db_table: session
        db_id_col: session_id
        db_data_col: session_value
        db_time_col: session_time

services:
    session.storage.pdo:
        class:     Symfony\Component\HttpFoundation\SessionStorage\PdoSessionStorage
        arguments: [@pdo, {}, %pdo.db_options%]

    pdo:
        class: PDO
        arguments:
                dsn:      "mysql:dbname=%database_name%"
                user:     %database_user%
                password: %database_password%

    whoot.facebook.user:
        class: Whoot\WhootBundle\Security\User\Provider\FacebookProvider
        arguments:
            facebook:    "@fos_facebook.api"
            userManager: "@whoot.user_manager"
            validator:   "@validator"
            container:   "@service_container"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        logging:  %kernel.debug%

    orm:
        auto_mapping: true
        auto_generate_proxy_classes: true
        proxy_namespace: Proxies
        proxy_dir: %kernel.cache_dir%/doctrine/orm/Proxies
        default_entity_manager: default
        metadata_cache_driver: array
        query_cache_driver: array
        result_cache_driver: array
        
# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
#    read_from:      %kernel.root_dir%/../web
#    write_to:       %kernel.root_dir%/../web
    filters:
        cssrewrite: ~
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

# This came with the symfony-standard distribution, not sure what it is.
jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

gravatar: ~

# FOS Facebook config
fos_facebook:
    file:   %kernel.root_dir%/../vendor/facebook/src/facebook.php
    alias:  facebook
    cookie: true
    permissions: [email, user_birthday, user_hometown, user_location]

# FriendsOfSymfony UserBundle Configuration
fos_user:
    db_driver:     orm
    firewall_name: main
    user_class:    Whoot\WhootUserBundle\Entity\User
    use_listener:  true
    from_email:
        address: marc@thewhoot.com
        sender_name: Marc
#    profile:
#        form:
#            type:               fos_user_profile
#            handler:            fos_user.profile.form.handler.default
#            name:               fos_user_profile_form
#            validation_groups:  [Profile]
#    change_password:
#        form:
#            type:               fos_user_change_password
#            handler:            fos_user.change_password.form.handler.default
#            name:               fos_user_change_password_form
#            validation_groups:  [ChangePassword]
    registration:
#        confirmation:
#            from_email: # Use this node only if you don't want the global email address for the confirmation email
#                address:        ...
#                sender_name:    ...
#            enabled:    false
#            template:   FOSUserBundle:Registration:email.txt.twig
        form:
                type:               whoot_user_registration
#            handler:            fos_user.registration.form.handler.default
#            name:               fos_user_registration_form
#            validation_groups:  [Registration]
#    resetting:
#        token_ttl: 86400
#        email:
#            from_email: # Use this node only if you don't want the global email address for the resetting email
#                address:        ...
#                sender_name:    ...
#            template:   FOSUserBundle:Resetting:email.txt.twig
#        form:
#            type:               fos_user_resetting
#            handler:            fos_user.resetting.form.handler.default
#            name:               fos_user_resetting_form
#            validation_groups:  [ResetPassword]
#    service:
#        mailer:                 fos_user.util.mailer.default
#        email_canonicalizer:    fos_user.util.email_canonicalizer.default
#        username_canonicalizer: fos_user.util.username_canonicalizer.default
#        user_manager:           fos_user.user_manager.default
#    encoder:
#        algorithm:          sha512
#        encode_as_base64:   false
#        iterations:         1
#    template:
#        engine: twig
#        theme:  FOSUserBundle::form.html.twig
#    group:
#        group_class:    ~ # Required when using groups
#        form:
#            type:               fos_user_group
#            handler:            fos_user.group.form.handler.default
#            name:               fos_user_group_form
#            validation_groups:  [Registration]
