# Security Configuration
security:

    factories:
        - "%kernel.root_dir%/../vendor/bundles/FOS/FacebookBundle/Resources/config/security_factories.xml"

    # strategy can be: none, migrate, invalidate
    #session_fixation_strategy: migrate
    providers:
        whoot_user:
            id: whoot.manager.user
        whoot_facebook:
            id: whoot.facebook.user

    firewalls:
        profiler:
            pattern:  /_profiler.*
            security: false

        wdt:
            pattern:  /_wdt.*
            security: false

        main:
            pattern:   .*
            form_login:
                provider:       whoot_user
                login_path:     /login
                use_forward:    false
                check_path:     /login_check
            fos_facebook:
                provider: whoot_facebook
                login_path: /login
                check_path: /fb/login_check
            logout: true
            anonymous: true

    access_control:
        # The WDT has to be allowed to anonymous users to avoid requiring the login with the AJAX request
        - { path: ^/_wdt/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # AsseticBundle paths used when using the controller for assets
        - { path: ^/js/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/css/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # URL of FOSUserBundle which need to be available to anonymous users
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # Secured part of the site
        - { path: ^/admin/, role: ROLE_ADMIN }
        # The rest of the site (optional ROLE_FACEBOOK if wanted)
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # For ESI
        - { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN:  [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    acl:
        connection: default