# Security Configuration
security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    # strategy can be: none, migrate, invalidate
    #session_fixation_strategy: migrate
    providers:
        fos_userbundle:
          id: fos_user.user_manager

    firewalls:
        profiler:
            pattern:  /_profiler.*
            security: false

        wdt:
            pattern:  /_wdt.*
            security: false

        backend:
            pattern: /ll-admin/.*
            http-basic: true

        api:
            pattern: /api/.*
            http-basic: true

        main:
            pattern:      .*
            form-login:
                provider:       fos_userbundle
                login_path:     /login
                check_path:     /login_check
                use_forward:    false
                failure_path:   null
            logout:       true
            anonymous:    true
#            switch_user: { role: ROLE_ADMIN, parameter: _switch_user }

#    access_control:
#        # The WDT has to be allowed to anonymous users to avoid requiring the login with the AJAX request
#        - { path: ^/_wdt/, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/_profiler/, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        # URL of the bundles which need to be available to anonymous users
#        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        # for the case of a failed login
#        - { path: ^/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/user/new$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/user/check-confirmation-email$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/user/confirm/, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/user/confirmed$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/user/request-reset-password$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/user/send-resetting-email$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/user/check-resetting-email$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/user/reset-password/, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        # Secured part of the site (all site here and an admin part for admin users)
#        - { path: ^/admin/, role: ROLE_ADMIN }
#        - { path: ^/.*, role: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    acl:
        connection: default