admin_manage_location:
    pattern:  /locations
    defaults:
        _controller: WhootBundle:Admin:location
    requirements:
        _method: GET

admin_location_create:
    pattern:  /locations/create
    defaults: { _controller: WhootBundle:Location:create }
    requirements:
        _method: POST

admin_location_city_delete:
    pattern:  /locations/delete/city/{cityId}
    defaults: { _controller: WhootBundle:Location:deleteCity }
    requirements:
        _method: GET|POST

admin_location_school_delete:
    pattern:  /locations/delete/school/{schoolId}
    defaults: { _controller: WhootBundle:Location:deleteSchool }
    requirements:
        _method: GET|POST

admin_location_school_create:
    pattern:  /locations/school/create
    defaults: { _controller: WhootBundle:Location:createSchool }
    requirements:
        _method: POST

admin_manage_trending:
    pattern:  /trending
    defaults:
        _controller: WhootBundle:Admin:trending
    requirements:
        _method: GET

admin_make_trendable:
    pattern:  /trending/add/{tagId}
    defaults:
        _controller: WhootBundle:Tag:makeTrendable
    requirements:
        _method: POST

admin_make_stoptag:
    pattern:  /stopword/add/{tagId}
    defaults:
        _controller: WhootBundle:Tag:makeStopword
    requirements:
        _method: POST

admin_home:
    pattern:  /
    defaults: { _controller: WhootBundle:Admin:home }
    requirements:
        _method: GET