api_follow_toggle:
    pattern:  /toggle/{userId}
    defaults:
        _controller: WhootBundle:Follow:toggle
        _format: json
    requirements:
        _method: POST|GET
        _format: json
        userId: \d+