list_new:
    pattern:  /new
    defaults: { _controller: WhootBundle:LList:new }
    requirements:
        _method: GET

list_create:
    pattern:  /new
    defaults: { _controller: WhootBundle:LList:new }
    requirements:
        _method: POST

list_edit:
    pattern:  /edit/{id}
    defaults: { _controller: WhootBundle:LList:edit }
    requirements:
        _method: GET

list_update:
    pattern:  /edit/{id}
    defaults: { _controller: WhootBundle:LList:update }
    requirements:
        _method: POST

list_user_add:
    pattern:  /add/u/{listId}
    defaults: { _controller: WhootBundle:LList:userAdd }
    requirements:
        _method: POST

list_user_delete:
    pattern:  /delete/u
    defaults: { _controller: WhootBundle:LList:userDelete }
    requirements:
        _method: POST

list_delete:
    pattern:  /delete/{id}
    defaults: { _controller: WhootBundle:LList:delete }

list_show:
    pattern:  /{id}/{slug}
    defaults: { _controller: WhootBundle:LList:show }
    requirements:
        _method: GET