ping_toggle:
    pattern:  /toggle/{userId}
    defaults: { _controller: WhootBundle:Ping:toggle, userId: 0 }
    requirements:
        _method: GET|POST

ping_show:
    pattern:  /{userId}
    defaults: { _controller: WhootBundle:Ping:show, _format: html }
    requirements:
        _method: GET
        format: html|xml