post_create:
    pattern:  /new
    defaults: { _controller: WhootBundle:Post:create }
    requirements:
        _method: POST

jive_toggle:
    pattern:  /jive/toggle/{postId}/{go}
    defaults: { _controller: WhootBundle:Post:jiveToggle, go: false }
    requirements:
        _method: GET|POST
        postId: \d+

open_invite_details:
    pattern:  /oi/{inviteId}
    defaults: { _controller: WhootBundle:Post:openInviteDetails }
    requirements:
        _method: GET
        inviteId: \d+