api_post_my:
    pattern:  /my
    defaults: { _controller: WhootBundle:Post:myPost, _format: json }
    requirements:
        _method: GET
        _format: json

api_post_feed:
    pattern:  /feed/{offset}.{limit}
    defaults:
        _controller: WhootBundle:Post:feed
        _format: json
        offset: 0
        limit: 0
        type: feed
    requirements:
        _method: GET
        _format: json

api_post_undecided:
    pattern:  /undecided/{offset}.{limit}
    defaults:
        _controller: WhootBundle:Post:feed
        _format: json
        offset: 0
        limit: 0
        type: undecided
    requirements:
        _method: GET
        _format: json

api_post_toggle:
    pattern:  /create
    defaults:
        _controller: WhootBundle:Post:create
        _format: json
    requirements:
        _method: POST
        _format: json

api_jive_toggle:
    pattern:  /jive/{postId}
    defaults:
        _controller: WhootBundle:Post:jiveToggle
        _format: json
    requirements:
        _method: POST|GET
        _format: json

api_post_details:
    pattern:  /{postId}
    defaults:
        _controller: WhootBundle:Post:postDetails
        _format: json
    requirements:
        _method: GET
        _format: json