post_create:
    pattern:  /create
    defaults: { _controller: WhootBundle:Post:create }
    requirements:
        _method: POST

post_details:
    pattern:  /{postId}
    defaults: { _controller: WhootBundle:Post:details }
    requirements:
        _method: GET
        postId: \d+