security:
    resource: "@WhootBundle/Resources/config/routing/security.yml"

user:
    resource: "@WhootBundle/Resources/config/routing/user.yml"
    prefix:   /u
    
post:
    resource: "@WhootBundle/Resources/config/routing/post.yml"
    prefix:   /p

follow:
    resource: "@WhootBundle/Resources/config/routing/follow.yml"
    prefix:   /f

ping:
    resource: "@WhootBundle/Resources/config/routing/ping.yml"
    prefix:   /ping

comment:
    resource: "@WhootBundle/Resources/config/routing/comment.yml"
    prefix:   /c

open_invite_feed:
  pattern: /oi
  defaults: { _controller: WhootBundle:Post:openInviteFeed }
  requirements:
    _method: GET

feed_filter_toggle:
    pattern:  /ac/tf/{postType}
    defaults: { _controller: WhootBundle:Core:toggleFeedFilter }
    requirements:
        postType:  working|low_in|low_out|big_out
        _method: GET|POST

feed_filter_change:
    pattern:  /ac/cf/{key}/{value}
    defaults: { _controller: WhootBundle:Core:changeFeedFilter }
    requirements:
        key:  feedSort
        value: popularity|created|activity
        _method: GET|POST

homepage:
    pattern:  /
    defaults: { _controller: WhootBundle:Core:home }