user:
    resource: "@WhootUserBundle/Resources/config/routing/routing.yml"

post:
    resource: "@WhootBundle/Resources/config/routing/post.yml"
    prefix:   /p

follow:
    resource: "@WhootBundle/Resources/config/routing/follow.yml"
    prefix:   /f

ping:
    resource: "@WhootBundle/Resources/config/routing/ping.yml"
    prefix:   /ping

comment:
    resource: "@WhootBundle/Resources/config/routing/comment.yml"
    prefix:   /c

list:
    resource: "@WhootBundle/Resources/config/routing/list.yml"
    prefix:   /l

user_api:
    resource: "@WhootUserBundle/Resources/config/routing/api.yml"
    prefix:   /api

api:
    resource: "@WhootBundle/Resources/config/routing/api.yml"
    prefix:   /api

feed_filter_toggle:
    pattern:  /ac/tf/{postType}
    defaults: { _controller: WhootBundle:Core:toggleFeedFilter }
    requirements:
        postType:  working|low_in|low_out|big_out
        _method: GET|POST

feed_filter_change:
    pattern:  /ac/cf/{key}/{value}
    defaults: { _controller: WhootBundle:Core:changeFeedFilter }
    requirements:
        key:  feedSort
        value: popularity|created|activity
        _method: GET|POST

deal_feed:
    pattern:  /deals
    defaults: { _controller: WhootBundle:Core:deals }

_security_check:
    pattern:  /login_check

_security_logout:
    pattern:  /logout

homepage:
    pattern:  /
    defaults: { _controller: WhootBundle:Core:home }