user_undecided:
    pattern:  /undecided
    defaults: { _controller: WhootBundle:User:undecided }
    requirements:
        _method: GET

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/user.xml"