user_upload_picture:
    pattern:  /upload-picture
    defaults: { _controller: WhootBundle:User:uploadPicture }
    requirements:
        _method: POST

user_followers:
    pattern:  /{username}/followers
    defaults: { _controller: WhootBundle:User:followers }
    requirements:
      _method: GET

user_following:
    pattern:  /{username}/following
    defaults: { _controller: WhootBundle:User:following }
    requirements:
      _method: GET

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/user.xml"