parameters:
    whoot.user_manager.class:                  Whoot\WhootUserBundle\Entity\UserManager

services:
    whoot.user_manager:
        class:        %whoot.user_manager.class%
        arguments:    ["@doctrine.orm.default_entity_manager"]