parameters:
    whoot.user_manager.class:                  Whoot\UserBundle\Entity\UserManager

services:
    whoot.user_manager:
        class:        %whoot.user_manager.class%
        arguments:
            - %fos_user.encoder.algorithm%
            - @fos_user.util.username_canonicalizer
            - @fos_user.util.email_canonicalizer
            - @doctrine.orm.default_entity_manager
            - %fos_user.model.user.class%