vote_create:
    pattern:  /new/{objectType}/{objectId}/{amount}
    defaults: { _controller: WhootVoteBundle:Vote:create }
    requirements:
        _method: POST
        objectType: Post|Invite
        objectId: \d+
        amount: 1